const SUPPORTED_SLASH_COMMANDS = Object.freeze([
  'about',
  'ask',
  'autojail',
  'automod',
  'ban',
  'bookmark',
  'calculator',
  'calendar',
  'case',
  'channelinfo',
  'changelog',
  'claim',
  'close',
  'color',
  'config',
  'crypto',
  'currency',
  'customcommand',
  'customize',
  'dashboard',
  'deafen',
  'define',
  'deposit',
  'disconnect',
  'domain',
  'economy',
  'economytop',
  'emojiinfo',
  'expandurl',
  'fakeperm',
  'fn',
  'give',
  'hardban',
  'help',
  'hide',
  'history',
  'id',
  'inventory',
  'invite',
  'iplookup',
  'kick',
  'linkpreview',
  'lock',
  'lockdown',
  'music',
  'mute',
  'nuke',
  'nsfw',
  'ping',
  'prefix',
  'premium',
  'presence',
  'purge',
  'reactionrole',
  'regex',
  'reminder',
  'role',
  'roleinfo',
  'rumishop',
  'savegif',
  'security',
  'selfprefix',
  'sell',
  'serverpremium',
  'setup',
  'shard',
  'shop',
  'slowmode',
  'softban',
  'spotify',
  'support',
  'tempban',
  'thresholds',
  'ticket',
  'todo',
  'transcript',
  'translate',
  'unban',
  'undeafen',
  'unhide',
  'unlock',
  'unlockdown',
  'unmute',
  'userpremium',
  'userinfo',
  'variables',
  'voicemove',
  'vote',
  'warn',
  'weather',
  'weekly',
  'whitelist',
  'withdraw',
  'work',
  'balance',
  'buy',
  'daily'
]);

const supportedSet = new Set(SUPPORTED_SLASH_COMMANDS);

function isSlashSupported(commandName) {
  return supportedSet.has(String(commandName || '').toLowerCase());
}

function listSupportedSlashCommands() {
  return [...SUPPORTED_SLASH_COMMANDS];
}

module.exports = {
  SUPPORTED_SLASH_COMMANDS,
  isSlashSupported,
  listSupportedSlashCommands
};
