server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:-youshallnotpass}"
    playerUpdateInterval: 5
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    sources:
      youtube: false
      bandcamp: true
      soundcloud: false
      twitch: false
      vimeo: true
      nico: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.17.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_VR
      - WEBEMBEDDED
  lavasrc:
    providers:
      - "ytsearch:%QUERY%"
      - "ytmsearch:%QUERY%"
    sources:
      spotify: false
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: true
      ytsearch: true
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:-}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:-}"
      preferAnonymousToken: true

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO

metrics:
  prometheus:
    enabled: false
