server:
  port: ${SERVER_PORT:3000}
  address: ${SERVER_ADDRESS:0.0.0.0}
  http2:
    enabled: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false

  server:
    password: "${LAVALINK_SERVER_PASSWORD:youshallnotpass}"

    sources:
      youtube: false
      bandcamp: true
      soundcloud: false
      twitch: false
      vimeo: true
      nico: false
      http: true
      local: false

    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
      - ANDROID_VR

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: INFO